version: '3.9'

services:

  node-express-app-db:
    image: postgres:latest
    container_name: node-express-app-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: UpRfgMLYBuHB8vxet2dg7KKBKLbhNPKVPDM7Dr9Jmw
      POSTGRES_DB: wallet
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - proxy-setinng-locale_nick-network

  node-express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - proxy-setinng-locale_nick-network

networks:
  proxy-setinng-locale_nick-network:
    external: true
