version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: UpRfgMLYBuHB8vxet2dg7KKBKLbhNPKVPDM7Dr9Jmw
      POSTGRES_DB : wallet
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
